### ISSUE TITLE
Design Docs Review #1

### ISSUE THREAD

**Issue by jliversi** [Emina288/GoodreadsFullStack#1]
Great start on your design docs, here are my notes so far:
**MVP LIST**
- [x] Remove logging in with OAuth (facebook, google, etc) from your MVP list for now. This can be a bonus for later.
- [x] Add logging in with a demo login to your auth MVP
- [x] I'd move "Recommendations" to a bonus, because writing an algorithm that doesn't do this randomly will be pretty involved.
- [x] Remove ability to buy book / linking to somewhere to buy it
- [x] For seeing a list of "related books", specify what makes it "related". Same author? Same genre? Flesh this out so you'll have a road map later on.
- [x] For reviews, you mention friends twice, but where would "friends" be implemented? This likely needs to be its own MVP and should be left to a bonus

**SCHEMA** 
- [x] Goodreads shows the user's real name in the dropdown menu, so add "name" column to users table. (This might be what you meant by username? So just change that) 
- [x] Books have a description on goodreads, so you should add this column to your books table
- [x] Authors should be their own table (so you can associate books with the same author). Change author on books table to author_id
- [x] Because authors will be a table, you should change other columns named "author_id" which reference the users table to "user_id" (to avoid confusion) 
- [x] You'll need to add a joins table for books and users which will store the information required for your last MVP (read, will read, etc). Two foreign keys and a third column to indicate state (read, will read, etc)
- [x] Are reviews the same as comments? If so, you should rename comments table to reviews and add a rating column.

**Comment by Emina288** [comment]
Should I add the bonus part later on if I think I will finish on time or should I have it all now? 
I also removed likes table because it was referring to friends posts.

**Comment by jliversi** [comment]
You can neglect including bonuses in your design docs for now
