### ISSUE TITLE
Design Docs Review - Sample State

### ISSUE THREAD

**Issue by jliversi** [Emina288/GoodreadsFullStack#2]
Great work on your sample state, only a few notes:
- [x] Change all snake_case to camelCase (this will all be on your frontend and we should be using camelCase in js).
- [x] Include `isbn`s  under books.
- [x] Include `bookIds` under bookshelves 
- [x] You'll want to include the information for your 6th MVP (read status). You can implement this in a few different ways. Probably the easiest would be adding keys under each user for `read`, `currentlyReading` and `willRead`, each pointing to an array of bookIds.

**Comment by Emina288** [comment]
Should I also include bookshelvesIds under books?

**Comment by Emina288** [comment]
Sholud I add a status read, currentlyReading or will read under every book or that's redundant?

**Comment by jliversi** [comment]
You should definitely include bookshelvesIds under books (nice catch!), and every book should have a status (even if that status is null because for the current user it’s none of those). This will just make it much easier to use the book on the BookShow page
